# Generated by Django 3.0.8 on 2020-09-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('main_ingredient', models.CharField(max_length=64)),
                ('quantity', models.CharField(max_length=64)),
            ],
        ),
    ]
