# Generated by Django 3.0.8 on 2020-10-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakfast',
            old_name='main_ingredient',
            new_name='ingredient',
        ),
        migrations.AddField(
            model_name='breakfast',
            name='meal_time',
            field=models.CharField(default='breakfast', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breakfast',
            name='measure',
            field=models.CharField(default='kg', max_length=64),
            preserve_default=False,
        ),
    ]
