# Generated by Django 3.0.8 on 2020-10-08 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0002_auto_20201007_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfast',
            name='meal_time',
        ),
    ]
