# Generated by Django 3.0.8 on 2020-10-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0003_remove_breakfast_meal_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('ingredient', models.CharField(max_length=64)),
                ('measure', models.CharField(max_length=64)),
                ('quantity', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('ingredient', models.CharField(max_length=64)),
                ('measure', models.CharField(max_length=64)),
                ('quantity', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('ingredient', models.CharField(max_length=64)),
                ('measure', models.CharField(max_length=64)),
                ('quantity', models.CharField(max_length=64)),
            ],
        ),
    ]
