# Generated by Django 3.0.8 on 2020-10-08 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0004_dinner_lunch_snack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakfast',
            old_name='day',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='dinner',
            old_name='day',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='lunch',
            old_name='day',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='snack',
            old_name='day',
            new_name='date',
        ),
    ]
