# Generated by Django 3.0.8 on 2020-10-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0005_auto_20201008_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('fat_sat', models.IntegerField()),
                ('fat_trans', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('carb', models.IntegerField()),
                ('fiber', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='breakfast',
            name='nutrition_parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dinner',
            name='nutrition_parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lunch',
            name='nutrition_parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snack',
            name='nutrition_parsed',
            field=models.BooleanField(default=False),
        ),
    ]
