# Generated by Django 3.0.8 on 2020-10-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0006_auto_20201011_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='day',
            field=models.DateField(),
        ),
    ]
