# Generated by Django 3.0.8 on 2020-10-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0007_auto_20201011_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='calories',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='carb',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='fat',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='fat_sat',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='fat_trans',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='fiber',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='protein',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='sugar',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
