# Generated by Django 3.0.8 on 2020-11-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0009_auto_20201104_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='cholesterol',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calendar',
            name='poly_fat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='calories',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='carbs',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='fat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='fiber',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='mono_fat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='potassium',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='protein',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='sat_fat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='sodium',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='sugar',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
