# Generated by Django 3.1.3 on 2020-12-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0011_auto_20201206_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='calories',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='goal',
            name='carbs',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='goal',
            name='fat',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='goal',
            name='protein',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
